version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.1

jobs:
  run-recaptcha-solver:
    docker:
      - image: cimg/python:3.9-browsers
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run Recaptcha Solver
          command: |
            . venv/bin/activate
            python recaptcha_solver.py
      - store_artifacts:
          path: screenshot.png
          destination: screenshot

workflows:
  recaptcha-solver:
    jobs:
      - run-recaptcha-solver
